### ISSUE TITLE
question: diff between exception.ignore and contextlib.suppress

### ISSUE THREAD

**Issue by Cologler** [flaggo/pydu#16]
what is the different between 

https://github.com/Prodesire/pydu/blob/b1693db3821960d007e20d972fa69851b39bcf22/pydu/exception.py#L4-L9

and `contextlib.suppress(*exceptions)`

**Comment by Cologler** [comment]
`misc.memoize` 和 `functools.lru_cache` 也很相似。有什么优点吗？

**Comment by Prodesire** [comment]
Well, I reimplement `exception.ignore`, so that it is same to `contextlib.suppress` on Python 3. But on Python 2, `exception.ignore` is still implement by self due to there is not `contextlib.suppress`.

**Comment by Prodesire** [comment]
`misc.memoize` aims to cache a value returned by method, so that when we use the method next time, it will just return the cached value.

Meanwhile, `functools.lru_cache` aims to cache least recently used value using LRU algorithm. See [wiki](http://en.wikipedia.org/wiki/Cache_algorithms#Least_Recently_Used). If we don't use the value frequently, the cache will be gone. And when we call the method next time, it will re-calculate because of no cache value exists.

**Comment by Cologler** [comment]
但 `lru_cache` 可以设置缓存大小啊，只要设置为 None 就不会抛弃过去的值了。

**Comment by Prodesire** [comment]
设置为 `None` 确实能达到效果，但这就有点类似于“杀鸡用牛刀”的感觉。之所以有 `msc.memoize` 是处于这样的考量：
- `functools.lru_cache` 在Python 3中才有，在Python 2中需额外实现
- 针对单纯缓存函数调用结果来说，LRU算法尽管能解决问题，但大材小用了，显得有些复杂
